### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by Gemorroj** [overblog/ActiveMqBundle#6]
Need to add more informative README.
For example, the description of the configuration of the bundle.

Add to config.yml:
```yaml
overblog_active_mq:
    connections:
        default:
            user: null
            password: null
            version: 1.1
            randomize_failover: false
            servers:
                - {uri: 'localhost:61613', useAsyncSend: true, startupMaxReconnectAttempts: null, maxReconnectAttempts: null}
    publishers:
        web:
            connection: 'default'
            options:
                type: 'queue'
                name: 'web'
    consumers:
        web:
            connection: 'default'
            handler: 'todo'
            options:
                type: 'queue'
                name: 'web'
                prefetchSize: 1
```
